### ISSUE TITLE
Problems loading with OmegaT 5.6.0

### ISSUE THREAD

**Issue by knochenhans** [dtr5/Forecat-OmegaT#10]
Hi, trying to load this with OmegaT 5.6.0 and Java 11 OpenJDK, I’m running into the following error:
```
20739: Fehler: Uncatched exception in thread [AWT-EventQueue-0] 
20739: Fehler: java.lang.NoClassDefFoundError: com/jgoodies/forms/layout/FormLayout 
20739: Fehler: 	at org.omegat.plugins.autocomplete.forecat.preferences.ForecatPreferencesDialog.<init>(Unknown Source) 
20739: Fehler: 	at org.omegat.plugins.autocomplete.forecat.ForecatMenu$2.actionPerformed(Unknown Source) 
20739: Fehler: 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) 
20739: Fehler: 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) 
20739: Fehler: 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) 
20739: Fehler: 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) 
20739: Fehler: 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369) 
20739: Fehler: 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020) 
20739: Fehler: 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064) 
20739: Fehler: 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635) 
20739: Fehler: 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342) 
20739: Fehler: 	at java.desktop/java.awt.Component.processEvent(Component.java:6400) 
20739: Fehler: 	at java.desktop/java.awt.Container.processEvent(Container.java:2263) 
20739: Fehler: 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011) 
20739: Fehler: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321) 
20739: Fehler: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843) 
20739: Fehler: 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) 
20739: Fehler: 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) 
20739: Fehler: 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) 
20739: Fehler: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307) 
20739: Fehler: 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772) 
20739: Fehler: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843) 
20739: Fehler: 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) 
20739: Fehler: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) 
20739: Fehler: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) 
20739: Fehler: 	at java.base/java.security.AccessController.doPrivileged(Native Method) 
20739: Fehler: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 
20739: Fehler: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) 
20739: Fehler: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745) 
20739: Fehler: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743) 
20739: Fehler: 	at java.base/java.security.AccessController.doPrivileged(Native Method) 
20739: Fehler: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 
20739: Fehler: 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) 
20739: Fehler: 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 
20739: Fehler: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 
20739: Fehler: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 
20739: Fehler: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 
20739: Fehler: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
20739: Fehler: 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) 
20739: Fehler: Caused by: java.lang.ClassNotFoundException: com.jgoodies.forms.layout.FormLayout 
20739: Fehler: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) 
20739: Fehler: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) 
20739: Fehler: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) 
20739: Fehler: 	... 39 more
```

Is there any chance to run this even with newer versions of OmegaT? ;)

**Comment by eltorre** [comment]
Hi Andre,

I have not been following the development of OmegaT lately, so I cannot say if the plugin will still work, even after fixing this problem. 

I am fairly sure the issue you report is due the "settings menu" which was coded in the style of OmegaT 3. I will have a quick look when I have a moment and let you know if this is fixed by providing the appropriate libraries or if this would require more work.

Daniel

**Comment by eltorre** [comment]
Hi Andre,

it seems release [1.0b](https://github.com/transducens/Forecat-OmegaT/releases/tag/1.0b) loads fine.

Can you please confirm?

Please let me know if the issue in #3 reproduces. 1.0b does not have the patch but I was never able to replicate the issue, so I do not know if it is actually needed.

Daniel

**Comment by knochenhans** [comment]
Hi, sorry, took me a bit to get back to this. OmegaT (using version 5.7.0 by now) loads fine with this and the plugin is listed under the plugins in OmegaT’s options, but I’m getting the same error output as above when I try to open the Preferences window for Forecat.
